---

version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.4.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
  kibana:
    image: kibana:7.4.0
    ports:
      - 5601:5601
    networks:
      - elastic
networks:
  elastic:
